### PR TITLE
add more section to homepage

### PR DESCRIPTION
**Pull request by Sreejit-Sengupto**

### CODE REVIEW

**Comment by Sreejit-Sengupto** [comment]
Don't merge. Kuch changes karenge

**Comment by capsule11** [comment]
Other companies section add hoga and why choose craftbox me jo image ke peeche waala component hai wo thora shi nhi lag rha and craftbox ki jagah use nilam packers

**Comment by Sreejit-Sengupto** [comment]
Acha. Tab merge kardo aur apne hisab se modification kardo

**Comment by capsule11** [comment]
hero sec ke buttons clickable nhi hai jab ham banaye the uss waqt bhi yhi issue aaraha tha pta nhi kyu usko dekh lena ekbaar

**Comment by Sreejit-Sengupto** [comment]
Button ki jagah Link lagega

**Pull request merged**
